---

# Specified version because of https://github.com/ansible/ansible/issues/17495
- name: Install docker-py 1.9.0 to fix Ansible issue 17495
  pip:
    name: docker-py
    version: 1.9.0
    state: present
  when: ansible_version is defined
    and ansible_version.full | version_compare('2.2.0.0', '<')

- name: Install docker-py (python <= 2.6)
  pip:
    name: docker-py
    state: present
  when: (ansible_version is not defined)
    or  (ansible_version is defined and ansible_version.full | version_compare('2.2.0.0', '>='))
    and (ansible_python_version | version_compare('2.7.0', '<'))

- name: Uninstall docker-py (python >= 2.7)
  pip:
    name: docker-py
    state: absent
  when: (ansible_version is not defined)
    or  (ansible_version is defined and ansible_version.full | version_compare('2.2.0.0', '>='))
    and (ansible_python_version | version_compare('2.7.0', '>='))

- name: Install docker (python >= 2.7)
  pip:
    name: docker
    state: present
  when: (ansible_version is not defined)
    or  (ansible_version is defined and ansible_version.full | version_compare('2.2.0.0', '>='))
    and (ansible_python_version | version_compare('2.7.0', '>='))
